# Generated by Django 4.1.7 on 2023-03-28 22:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Не более 5000 символов', max_length=5000, null=True),
        ),
    ]
