# Generated by Django 4.1.7 on 2023-04-04 21:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 символов', max_length=200)),
                ('info', ckeditor.fields.RichTextField(blank=True, help_text='Не более 5000 символов', max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/trainer/')),
            ],
            options={
                'verbose_name': 'Добавить тренера',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
